homeassistant:

device_tracker:
  - platform: experiaboxv10
    host: 192.168.2.254
    username: !secret ROUTER_USERNAME
    password: !secret ROUTER_PASSWORD
    new_device_defaults:
      track_new_devices: true
    interval_seconds: 15
    consider_home: 300
